name:                slang-compiler
version:             0.1.0.0
github:              "hnefatl/slang-compiler"
license:             BSD3
author:              "Keith Collister"
maintainer:          "collisterkeith@gmail.com"
copyright:           "2018 Keith Collister"

extra-source-files:
- README.md
- "**/*.x"
- "**/*.y"

build-tools:
- alex
- happy

# Metadata used when publishing your package
synopsis:            A simple compiler for the SLang language.
# category:          Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hnefatl/slang-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- array
- lens
- random

library:
  source-dirs: src
  exposed-modules:

ghc-options:
- -Wall

executables:
  slangc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slang-compiler
    - lens

tests:
  compiler-test:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slang-compiler
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    - directory
    - filepath